name: "Setup Rust Environment"
description: "Set up Rust toolchain with caching"
inputs:
  toolchain:
    description: "Rust toolchain to install"
    required: false
    default: "stable"
  components:
    description: "Additional components to install"
    required: false
    default: ""
  cache-key-suffix:
    description: "Additional suffix for cache key"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ inputs.toolchain }}${{ inputs.cache-key-suffix }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ inputs.toolchain }}${{ inputs.cache-key-suffix }}-
          ${{ runner.os }}-cargo-${{ inputs.toolchain }}-
          ${{ runner.os }}-cargo-
